[package]
name = "mips_app"
version = "0.1.0"
edition = "2021"

[dependencies]
mips_lib = { path = "../mips_lib" }
vulkano = "0.35.1"
winit = "0.30.9"
thiserror = "2.0.11"
anyhow = "1.0.97"
log = "0.4.26"